### ISSUE TITLE
Rubocop scanning issues

### ISSUE THREAD

**Issue by nickific** [arthurnn/code-scanning-rubocop#11]
Looks like the rubocop action is failing due to a conflict in ruby versions.

**Comment by arthurnn** [comment]
sorry, can you describe the problem a bit more

**Comment by endormi** [comment]
I had the same issue. I was using this way first `bundle add code-scanning-rubocop --version 0.3.0 --skip-install`. I fixed the issue by running `bundle add code-scanning-rubocop --skip-install`.

I don't know your error result, but if you haven't tried that you should.

**Comment by arthurnn** [comment]
The more reliable way to use this extension is to add the gem to your Gemfile, so you will not need to `bundle add` in actions. see https://github.com/arthurnn/code-scanning-rubocop#gem-installation--usage-in-a-custom-action
