### ISSUE TITLE
Workflow assumes a Gemfile

### ISSUE THREAD

**Issue by sampart** [arthurnn/code-scanning-rubocop#7]
This is a bit of an edge case, but I tried using the action on a testing repo which contained Ruby code but didn't have a Gemfile, and it failed.

```
Run bundle add code-scanning-rubocop --version 0.2.0 --skip-install
  bundle add code-scanning-rubocop --version 0.2.0 --skip-install
  shell: /bin/bash -e {0}
  env:
    PATH: /home/runner/.rubies/ruby-2.6.6/bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin
Could not locate Gemfile
##[error]Process completed with exit code 10.
```

Full output: https://github.com/Anthophila/sampart-test/actions/runs/107999573

I had to add a Gemfile containing `source "https://rubygems.org"` (a blank Gemfile [didn't work](https://github.com/Anthophila/sampart-test/actions/runs/108005339)) to get this working.

As I say, it's unlikely we'll see this much in real-world usage, but I thought it worth mentioning.

**Comment by arthurnn** [comment]
I think if you are not using bundler, thus don't have a Gemfile, you might be at your own building and running rubocop in action. Then you would have to use the 'Custom action' part from the docs. https://github.com/arthurnn/code-scanning-rubocop#gem-installation--usage-in-a-custom-action
